[package]
name = "viewport"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1"
winit = "0.27"
wgpu = "0.15"
env_logger = "0.10"
log = "0.4"
bytemuck = { version = "1.12", features = [ "derive" ] }
